name: Create tag
description: Creates and pushes a git tag

inputs:
  tag:
    description: The tag name to create
    required: true

runs:
  using: composite
  steps:
    - name: Create and push tag
      shell: bash
      env:
        TAG: ${{ inputs.tag }}
      run: |
        git tag "$TAG"
        git push origin "$TAG"
