name: Get remote package.json version
description: Retrieves semantic version from remote repository

inputs:
  package-name:
    description: The npm package name to look up
    required: true

outputs:
  version:
    description: The remote package version
    value: ${{ steps.version.outputs.result }}

runs:
  using: composite
  steps:
    - name: Read version
      id: version
      shell: bash
      env:
        PACKAGE_NAME: ${{ inputs.package-name }}
      run: |
        set +e
        version=$(npm view "$PACKAGE_NAME" version)
        echo "result=$version" >> "$GITHUB_OUTPUT"
