name: Run dependency review
description: Runs a dependency review on pull requests

inputs:
  comment-summary-in-pr:
    description: Whether to comment a summary of the dependency review in the pull request
    required: false
    default: 'always'

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Dependency review
      uses: actions/dependency-review-action@v5
      with:
        comment-summary-in-pr: ${{ inputs.comment-summary-in-pr }}
