name: Publish package to npm
description: Publishes an npm package to the registry

inputs:
  working-directory:
    description: The working directory to run npm publish in
    required: true

runs:
  using: composite
  steps:
    - name: Publish package
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: npm publish --access public
