# Only supports releases to NPM at the moment
name: Release a node package, publish to NPM, and create & push a git tag

on:
  workflow_call:
    inputs:
      node-version:
        description: Node.js version to use
        required: false
        type: string
        default: '24'
      artifact-name:
        description: Name of the build artifact to download
        required: false
        type: string
        default: dist
      working-directory:
        description: The working directory to run npm commands in
        required: false
        type: string
        default: '.'
      artifact-path:
        description: Path to download the artifact to
        required: false
        type: string
        default: dist

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Get local package information
        id: local
        uses: aspithost/actions/node/get-local-package-information@v2
        with:
          working-directory: ${{ inputs.working-directory }}

      - name: Get remote package version
        id: remote
        uses: aspithost/actions/npm/get-remote-package-version@v2
        with:
          package-name: ${{ steps.local.outputs.name }}

      - name: Setup Node
        if: steps.local.outputs.version != steps.remote.outputs.version
        uses: actions/setup-node@v6
        with:
          node-version: ${{ inputs.node-version }}

      - name: Download build artifact
        if: inputs.artifact-name != '' && steps.local.outputs.version != steps.remote.outputs.version
        uses: actions/download-artifact@v8
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.working-directory }}/${{ inputs.artifact-path }}

      - name: Publish package
        if: steps.local.outputs.version != steps.remote.outputs.version
        uses: aspithost/actions/npm/publish@v2
        with:
          working-directory: ${{ inputs.working-directory }}

      - name: Create and push tag
        if: steps.local.outputs.version != steps.remote.outputs.version
        uses: aspithost/actions/git/create-and-push-tag@v2
        with:
          tag: ${{ steps.local.outputs.name }}@${{ steps.local.outputs.version }}
